# Generated by Django 3.0 on 2019-12-16 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_handles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basehandle',
            options={'ordering': ['handle']},
        ),
        migrations.AlterModelOptions(
            name='similarhandles',
            options={'ordering': ['handle']},
        ),
        migrations.RenameField(
            model_name='similarhandles',
            old_name='base_handle_date',
            new_name='base_handle',
        ),
        migrations.RemoveField(
            model_name='basehandle',
            name='date_pulled',
        ),
        migrations.RemoveField(
            model_name='basehandle',
            name='id',
        ),
        migrations.AddField(
            model_name='similarhandles',
            name='date_pulled',
            field=models.DateField(default=datetime.date(2019, 12, 15)),
        ),
        migrations.AlterField(
            model_name='basehandle',
            name='handle',
            field=models.CharField(help_text='Please do not include the @ symbol, and use only valid Twitter handle chracters', max_length=15, primary_key=True, serialize=False, unique_for_date='date_pulled'),
        ),
    ]
