# Generated by Django 2.0 on 2019-12-16 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_handles', '0004_auto_20191215_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarhandles',
            name='date_pulled',
        ),
        migrations.AddField(
            model_name='basehandle',
            name='date_pulled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='basehandle',
            name='handle',
            field=models.CharField(help_text='Please do not include the @ symbol, and use only valid Twitter handle characters', max_length=15, primary_key=True, serialize=False, unique_for_date='date_pulled'),
        ),
        migrations.AlterField(
            model_name='similarhandles',
            name='handle',
            field=models.CharField(max_length=15),
        ),
    ]
