# Generated by Django 2.0 on 2019-12-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_handles', '0006_auto_20191216_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarhandles',
            name='bio',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='similarhandles',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='similarhandles',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='similarhandles',
            name='number_following',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='similarhandles',
            name='number_of_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='similarhandles',
            name='number_of_tweets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
