# Generated by Django 2.0 on 2019-12-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_handles', '0007_auto_20191216_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehandle',
            name='handle',
            field=models.CharField(error_messages={'unique': 'Sorry, info for that handle has already been gathered today. You can view it under "Browse Base Handles"!'}, help_text='Please do not include the @ symbol, and use only valid Twitter handle characters', max_length=15, primary_key=True, serialize=False, unique_for_date='date_pulled'),
        ),
    ]
